# Generated by Django 5.2.4 on 2025-08-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_difficulty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_points',
        ),
    ]
