# Generated by Django 5.2.4 on 2025-08-23 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0002_delete_learninggoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('first course', 'First Course Completed'), ('quiz master', 'Quiz Master'), ('streak 7', '7 Day Streak'), ('streak 30', '30 Day Streak'), ('fast learner', 'Fast Learner')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='achievement',
            unique_together={('user', 'achievement_type', 'earned_at')},
        ),
    ]
